export default {
  generateUploadToken: 'generateUploadToken',
  getBucketList: 'getBucketList',
  getResourceList: 'getResourceList',
  updateBucket: 'updateBucket',
  getBucketDomains: 'getBucketDomains',
  deleteBucketFiles: 'deleteBucketFiles',
  getOverviewInfo: 'getOverviewInfo',
  open: 'open',
  readPaths: 'readPaths',
  serverUploadFiles: 'serverUploadFiles',
  fetchResourceToBucket: 'fetchResourceToBucket',
  moveBucketFiles: 'moveBucketFiles',
  refreshFiles: 'refreshFiles',
  refreshDirs: 'refreshDirs',
  showOpenDialog: 'showOpenDialog',
  getSettings: 'getSettings',
  updateSettings: 'updateSettings',
  resetSettings: 'resetSettings',
  login: 'login',
  deleteUsedCSP: 'deleteUsedCSP',
  downloadFiles: 'downloadFiles',
  downloadManager_progress: 'downloadManager_progress',
  downloadManager_cancel: 'downloadManager_cancel',
  downloadManager_error: 'downloadManager_error',
}
